[package]
name = "httprepeater"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
reqwest = { version = "0.12.7" }
tokio = { version = "1.40.0", features = ["full"] }
